---
# Source: microapp/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
    - port: 3000
      targetPort: 3000
---
# Source: microapp/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tickets
spec:
  selector:
    app: tickets
  ports:
    - port: 4000
      targetPort: 4000
---
# Source: microapp/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: "wala12/auth:latest"
          ports:
            - containerPort: 3000
---
# Source: microapp/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: "wala12/tickets:latest"
          ports:
            - containerPort: 4000
