apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: {{ .Values.services.payment.replicaCount }}
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: "{{ .Values.services.payment.image }}:{{ .Values.services.payment.tag }}"
          ports:
            - containerPort: {{ .Values.services.payment.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    app: payment
  ports:
    - port: {{ .Values.services.payment.port }}
      targetPort: {{ .Values.services.payment.port }}
  type: {{ .Values.service.type }}
