apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: {{ .Values.services.auth.replicas }}

  selector:
    matchLabels:
      app: auth

  template:
    metadata:
      labels:
        app: auth

    spec:
      containers:
        - name: auth
          image: "{{ .Values.services.auth.image }}:{{ .Values.services.auth.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}

          ports:
            - containerPort: {{ .Values.services.auth.port }}

          env:
            - name: MONGO_URI
              value: {{ .Values.services.auth.env.MONGO_URI | quote }}

            - name: RABBITMQ_URL
              value: {{ .Values.services.auth.env.RABBITMQ_URL | quote }}

            - name: JWT_KEY
              value: {{ .Values.services.auth.env.JWT_KEY | quote }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.auth.service }}

spec:
  type: ClusterIP

  selector:
    app: auth

  ports:
    - port: {{ .Values.services.auth.port }}
      targetPort: {{ .Values.services.auth.port }}
      protocol: TCP
