{{- if .Values.services }}
{{- range $name, $svc := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
spec:
  replicas: {{ default 1 $svc.replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ $svc.image }}:{{ default "latest" $svc.tag }}"
          ports:
            - containerPort: {{ default 3000 $svc.port }}
---
{{- end }}
{{- end }}
