apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets
spec:
  replicas: {{ .Values.services.tickets.replicas }}
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: "{{ .Values.services.tickets.image }}:{{ .Values.services.tickets.tag }}"
          ports:
            - containerPort: {{ .Values.services.tickets.port }}

          env:
            - name: JWT_KEY
              value: {{ .Values.services.tickets.env.JWT_KEY | quote }}

            - name: RABBITMQ_URL
              value: {{ .Values.services.tickets.env.RABBITMQ_URL | quote }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.tickets.service }}
spec:
  selector:
    app: tickets
  ports:
    - port: {{ .Values.services.tickets.port }}
      targetPort: {{ .Values.services.tickets.port }}
  type: ClusterIP
