apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client

spec:
  replicas: {{ .Values.services.client.replicas }}

  selector:
    matchLabels:
      app: client

  template:
    metadata:
      labels:
        app: client

    spec:
      containers:
        - name: client
          image: "{{ .Values.services.client.image }}:{{ .Values.services.client.tag }}"
          imagePullPolicy: Always

          ports:
            - containerPort: {{ .Values.services.client.port }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.client.service }}

spec:
  selector:
    app: client

  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.services.client.port }}

  type: ClusterIP
