apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration
spec:
  replicas: {{ .Values.services.expiration.replicas }}
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: "{{ .Values.services.expiration.image }}:{{ .Values.services.expiration.tag }}"
          ports:
            - containerPort: {{ .Values.services.expiration.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.expiration.service }}
spec:
  selector:
    app: expiration
  ports:
    - port: {{ .Values.services.expiration.port }}
      targetPort: {{ .Values.services.expiration.port }}
  type: ClusterIP
