{{- if .Values.mongo.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: {{ .Values.mongo.replicaCount }}
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.mongo.image }}:{{ .Values.mongo.tag }}"
          ports:
            - containerPort: {{ .Values.mongo.port }}
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data

      volumes:
        - name: mongo-data
          {{- if .Values.mongo.persistence.enabled }}
          persistentVolumeClaim:
            claimName: mongo-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.port }}

{{- end }}
