{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microapp-ingress
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /auth/api/
            pathType: Prefix
            backend:
              service:
                name: auth
                port:
                  number: 3000

          - path: /tickets
            pathType: Prefix
            backend:
              service:
                name: tickets
                port:
                  number: 3000

          - path: /payment
            pathType: Prefix
            backend:
              service:
                name: payment
                port:
                  number: 3000

          - path: /expiration
            pathType: Prefix
            backend:
              service:
                name: expiration
                port:
                  number: 3000

          - path: /orders
            pathType: Prefix
            backend:
              service:
                name: orders
                port:
                  number: 3000
{{- end }}
