{{- if and .Values.rabbitmq .Values.rabbitmq.enabled }}

apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{ .Values.rabbitmq.name | default "rabbit-service" }}

spec:
  replicas: {{ .Values.rabbitmq.replicas | default 1 }}

  service:
    type: {{ .Values.rabbitmq.service.type | default "ClusterIP" }}

  auth:
    username: {{ .Values.rabbitmq.auth.username | default "wala" }}
    password: {{ .Values.rabbitmq.auth.password | default "Root123!" }}

  resources:
    requests:
      cpu: {{ .Values.rabbitmq.resources.cpu | default "100m" }}
      memory: {{ .Values.rabbitmq.resources.memory | default "128Mi" }}
    limits:
      cpu: {{ .Values.rabbitmq.resources.cpu | default "100m" }}
      memory: {{ .Values.rabbitmq.resources.memory | default "128Mi" }}

  rabbitmq:
    additionalConfig: |
      log.console.level = {{ .Values.rabbitmq.config.logLevel | default "info" }}
      channel_max = {{ .Values.rabbitmq.config.channelMax | default 2047 }}

{{- end }}
