global:
  imagePullPolicy: IfNotPresent

service:
  type: ClusterIP

services:

  auth:
    image: hammamioumayma/auth
    tag: latest
    replicas: 2
    port: 3000
    service: auth-service
    env:
      MONGO_URI: mongodb://mongo-service:27017/auth
      RABBITMQ_URL: amqp://rabbit-service:5672
      JWT_KEY: my-secret-key

  orders:
    image: hammamioumayma/orders
    tag: latest
    replicas: 2
    port: 3000
    service: orders-service
    env:
      MONGO_URI: mongodb://mongo-service:27017/orders
      RABBITMQ_URL: amqp://rabbit-service:5672
      JWT_KEY: my-secret-key

  payment:
    image: hammamioumayma/payments
    tag: latest
    replicas: 2
    port: 3000
    service: payments-service
    env:
      RABBITMQ_URL: amqp://rabbit-service:5672
      STRIPE_KEY: sk_test_dummy_key

  tickets:
    image: hammamioumayma/tickets
    tag: latest
    replicas: 2
    port: 3000
    service: tickets-service
    env:
      JWT_KEY: my-secret-key

  expiration:
    image: hammamioumayma/expiration
    tag: latest
    replicas: 2
    port: 3000
    service: expiration-service

  client:
    image: hammamioumayma/client
    tag: latest
    replicas: 2
    port: 3000
    service: client-service

mongo:
  enabled: true
  image: mongo
  tag: "6.0"
  port: 27017
  replicaCount: 1
  persistence:
    enabled: false

rabbitmq:
  enabled: true
  name: rabbit-service
  replicas: 1
  resources:
    cpu: "1000m"
    memory: "512Mi"
  config:
    logLevel: debug
    channelMax: 1700
    defaultUser: guest
    defaultPass: guest
    admin: true
