
# =========================
# GLOBAL
# =========================
global:
  imagePullPolicy: IfNotPresent

# Default service type (optional fallback)
service:
  type: ClusterIP

# =========================
# MICROSERVICES
# =========================
services:
  auth:
    image: wala12/auth
    tag: 8b5bc4c
    replicas: 2
    port: 3000
    service: auth-service
    env:
      MONGO_URI: mongodb://mongo-service:27017/auth
      RABBITMQ_URL: amqp://rabbit-service:5672
      JWT_KEY: my-secret-key

  tickets:
    image: wala12/tickets
    tag: 8b5bc4c
    replicas: 2
    port: 3000
    service: tickets-service

  payment:
    image: wala12/payments
    tag: 8b5bc4c
    replicas: 2
    port: 3000
    service: payments-service

  expiration:
    image: wala12/expiration
    tag: e438b61
    replicas: 2
    port: 3000
    service: expiration-service

  orders:
    image: wala12/orders
    tag: 8b5bc4c
    replicas: 2
    port: 3000
    service: orders-service
    env:
      MONGO_URI: mongodb://mongo-service:27017/orders
      RABBITMQ_URL: amqp://rabbit-service:5672

  client:
    image: wala12/client
    tag: latest
    replicas: 2
    port: 3000
    service: client-service

# =========================
# INGRESS
# =========================
ingress:
  className: nginx
  enabled: true

  hosts:
    rabbit:
      host: rabbitlokal.com
      service: rabbit-service
      port: 15672
      path: /

    app:
      host: ticketapp.com
      path: /

# =========================
# MONGODB
# =========================
mongo:
  enabled: true
  image: mongo
  tag: "6.0"
  port: 27017
  replicaCount: 1

  persistence:
    enabled: false

# =========================
# RABBITMQ
# =========================
rabbitmq:
  enabled: true
  name: rabbit-service
  replicas: 1

  resources:
    cpu: "1000m"
    memory: "0.6Gi"

  config:
    logLevel: debug
    channelMax: 1700
    defaultUser: guest
    defaultPass: guest
    admin: true
