
global:
  imageTag: latest
  imagePullPolicy: IfNotPresent

# =========================
# MICROSERVICES
# =========================
services:
  auth:
    replicaCount: 2
    image: wala12/auth
    tag: 8b5bc4c
    port: 3000

  tickets:
    replicaCount: 2
    image: wala12/tickets
    tag: latest
    port: 3000

  payment:
    replicaCount: 2
    image: wala12/payments
    tag: 8b5bc4c
    port: 3000

  expiration:
    replicaCount: 2
    image: wala12/expiration
    tag: e438b61
    port: 3000

  orders:
    replicaCount: 2
    image: wala12/orders
    tag: 8b5bc4c
    port: 3000

  client:
    replicaCount: 2
    image: wala12/client
    tag: latest
    port: 3000


# =========================
# INGRESS (STRUCTURED MODEL)
# =========================
ingress:
  className: nginx
  enabled: true

  hosts:
    rabbit:
      host: rabbitlokal.com
      service: rabbit-service
      port: 15672
      path: /

    app:
      host: ticketapp.com

# =========================
# MONGODB
# =========================
mongo:
  enabled: true
  image: mongo
  tag: 6.0
  port: 27017
  replicaCount: 1

  persistence:
    enabled: false


# =========================
# RABBITMQ (Operator CRD)
# =========================
rabbitmq:
  enabled: true
  name: rabbit-service

  replicas: 1

  resources:
    cpu: "1000m"
    memory: "0.6Gi"

  config:
    logLevel: debug
    channelMax: 1700
    defaultUser: guest
    defaultPass: guest
    admin: true
